# Generated by Django 5.0.2 on 2024-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car_delete_product_alter_student_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
