apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata: 
  name: my-pyapp
  namespace: argocd 
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  source: 
    repoURL: https://github.com/Kritik72/Django-learnings-projects
    targetRevision: main
    path: k8s-manifests
  project: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true