# Generated by Django 5.0.2 on 2024-02-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='unique',
            new_name='student_email',
        ),
    ]
