name: Build and Push Docker Image

on:
  push:
    branches: [ main ] 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: kritik78
        password: Admin @7890

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: kritik78/my-pyapp-k8s-version:latest

    - name: Update deployment YAML with new image tag
      run: |
        sed -i "s|REPLACEME_TAG|${{ github.sha }}|g" k8s-manifests/deployment.yaml

    - name: Commit updated manifest
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s-manifests/deployment.yaml
        git commit -m "Update deployment image to ${{ github.sha }}"
        git push